import datetime
from pathlib import Path
import structlog
from jinja2 import Environment, FileSystemLoader, DictLoader, ChoiceLoader, select_autoescape
from weasyprint import HTML

logger = structlog.get_logger(__name__)

def block_url_fetcher(url):
    """Odrzuca każde żądanie sieciowe i plikowe podczas renderowania PDF, nie powodując crashu."""
    logger.warning("An attempt by WeasyPrint to retrieve a resource has been blocked (Potential SSRF/LFI)", url=url)
    # Zwraca pusty słownik zasobu zgodnie z API WeasyPrint
    return {
        'string': b'',
        'mime_type': 'text/plain',
        'encoding': 'utf-8'
    }


class NIS2ReportGenerator:
    """Generator sformalizowanych raportów PDF zgodnych z wymogami NIS2."""

    def __init__(self, template_dir: Path):
        loaders = []
        
        # 1. Próba załadowania szablonów z dysku (jeśli użytkownik zamontował własne np. przez wolumen)
        if template_dir.exists() and template_dir.is_dir():
            loaders.append(FileSystemLoader(template_dir))
            
        # 2. Fallback: Domyślny szablon w pamięci (odporny na Read-Only FS w kontenerach)
        loaders.append(DictLoader({"report.html": self._get_default_template_string()}))
            
        # Zabezpieczenie przed Server-Side Template Injection (SSTI)
        self.env = Environment(
            loader=ChoiceLoader(loaders), # Użycie kaskadowego ładowania
            autoescape=select_autoescape(['html', 'xml']),
            trim_blocks=True,
            lstrip_blocks=True
        )

    def _get_default_template_string(self) -> str:
        """Zwraca domyślny szablon HTML bezpośrednio z pamięci RAM."""
        return """
        <!DOCTYPE html>
        <html lang="en-US">
        <head>
            <meta charset="UTF-8">
            <title>Aegis-LLM Audit Report (NIS2)</title>
            <style>
                body { font-family: Arial, sans-serif; color: #333; line-height: 1.6; margin: 40px; }
                h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
                h2 { color: #2980b9; margin-top: 30px; }
                .metadata { background: #ecf0f1; padding: 15px; border-radius: 5px; margin-bottom: 30px; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid #bdc3c7; padding: 12px; text-align: left; }
                th { background-color: #34495e; color: white; }
                .vuln-true { color: #e74c3c; font-weight: bold; }
                .vuln-false { color: #27ae60; }
                .evidence { background: #f9f9f9; padding: 10px; border-left: 4px solid #e74c3c; font-family: monospace; font-size: 0.9em; white-space: pre-wrap; word-wrap: break-word; }
                .footer { margin-top: 50px; font-size: 0.8em; color: #7f8c8d; text-align: center; border-top: 1px solid #bdc3c7; padding-top: 10px; }
            </style>
        </head>
        <body>
            <h1>LLM Security Audit Report</h1>
            <div class="metadata">
                <p><strong>Audit target:</strong> {{ target_url }}</p>
                <p><strong>Generation date:</strong> {{ date }}</p>
                <p><strong>Compliance:</strong> </p>
            </div>

            <h2>1. Summary of Vulnerabilities (Prompt Injection)</h2>
            <table>
                <thead>
                    <tr>
                        <th>Vector ID</th>
                        <th>Status</th>
                        <th>Time (ms)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for result in pi_results %}
                    <tr>
                        <td>{{ result.payload_id }}</td>
                        <td class="{% if result.is_vulnerable %}vuln-true{% else %}vuln-false{% endif %}">
                            {% if result.is_vulnerable %}VULNERABLE{% else %}SECURE{% endif %}
                        </td>
                        <td>{{ result.response_time_ms }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <h2>2. Incident Log</h2>
            <p>The logs below serve as evidence of successful manipulation of the model.</p>
            {% for result in pi_results %}
                {% if result.is_vulnerable %}
                    <h3>Vector: {{ result.payload_id }}</h3>
                    <!-- FIX: Limit the length of rendered text to 1,500 characters (Protection against WeasyPrint OOM) -->
                    <div class="evidence">{{ result.matched_evidence | truncate(1500, True, '... [TEXT TRUNCATED - SEE THE FULL LOG IN THE JSON REPORT]') }}</div>
                {% endif %}
            {% endfor %}

            <div class="footer">
                Automatically generated by the Aegis-LLM DAST Scanner. Confidential document.
            </div>
        </body>
        </html>
        """

    def generate_pdf(self, target_url: str, pi_results: list, output_path: Path):
        """Renderuje dane do HTML i konwertuje na PDF."""
        try:
            template = self.env.get_template("report.html")
            
            # Renderowanie HTML z danymi
            html_out = template.render(
                target_url=target_url,
                date=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                pi_results=pi_results
            )
            
            # Wyłączenie pobierania zewnętrznych zasobów przez WeasyPrint
            # Zapobiega atakom SSRF (Server-Side Request Forgery) podczas generowania PDF
            HTML(string=html_out).write_pdf(
                target=str(output_path),
                presentational_hints=True,
                optimize_size=('fonts', 'images'),
                url_fetcher=block_url_fetcher  # <--- NAPRAWA LUKI SSRF/LFI
            )
            logger.info("A PDF report has been generated", path=str(output_path))
            
        except Exception as e:
            logger.error("Error while generating the PDF", error=str(e))
            raise